---
abstract: 'Wrapped HTTP::Tiny with timeout and retry'
author:
  - 'Chen Gang <yikuyiku.com@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Retry
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Tiny: 0.017
version: 0.01
